<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\MediaFlow.Core\MediaFlow.Core.csproj" />
    <ProjectReference Include="..\MediaFlow.Application\MediaFlow.Application.csproj" />
    <ProjectReference Include="..\MediaFlow.Infrastructure\MediaFlow.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MQTTnet" Version="5.2.0.1603" />
  </ItemGroup>
</Project>
